indentation_style = "Tabs"              # "Tabs", "Spaces" or "Auto"
newline_style = "Unix"                  # "Unix", "Windows" or "Auto"
attr_value_brace_style = "WhenRequired" # "Always", "AlwaysUnlessLit", "WhenRequired" or "Preserve"
